### PR TITLE
change ExpireIn type to int

### PR DESCRIPTION
**Pull request by jgsqware**
Signed-off-by: Julien Garcia Gonzalez <julien@giantswarm.io>

Since this morning, I got this when I try to login to any installation via gsctl:

```
gsctl login --sso --endpoint https://api.g8s.REDACTED --verbose

Your browser should now be opening:
https://giantswarm.REDACTED

Attempt to run the OAuth2 PKCE workflow with a local callback HTTP server failed.
Something went wrong during SSO
Unable to parse response. Possibly Auth0 service is having trouble. Try again later.: sso error
Please contact the Giant Swarm support team or try the command again later.
```

After checking the `PKCEResponse`, it appears that I get the correct body 

```
REDACTED
```

and got this error in Json Marshalling:

```
json: cannot unmarshal number into Go struct field PKCEResponse.expires_in of type string
```

I changed the struct field type from `string` to `int`.

### CODE REVIEW

**Review by marians — DISMISSED** [review]
Modifications in `gscliauth` have to be done in https://github.com/giantswarm/gscliauth

**Comment by oponder** [comment]
This seems somehow fixed here already: https://github.com/giantswarm/gscliauth/pull/6/files

@jgsqware: Update dependencies and try again?

**Comment by jgsqware** [comment]
@oponder what do you mean, the `gsctl` deps would be behind?

**Comment by oponder** [comment]
Yeah it would appear so, since the change you made in this PR is to a vendored dependency, and I see that in the repo of that dependency (`gscliauth`) the change you attempted to make has already been made.

**Comment by marians** [comment]
Where is the `:troll:` emoji when you need it? 😛

**Comment by jgsqware** [comment]
lol
I will revert and update deps

**Comment by jgsqware** [comment]
Vendors updated and works fine now

**Review by oponder — APPROVED** [review]

**Pull request merged**
