### PR TITLE
Modify install and execution of packr to work in CI, too

### PR DESCRIPTION
**Pull request by marians**

### CODE REVIEW

**Comment by sslavic** [comment]
@marians now when I build locally master, build fails:

```
$ make clean install
rm -rf bin-dist build go-build-cache release ./gsctl
docker run --rm \
	-v /home/stevo/git/giantswarm/gsctl:/go/src/github.com/giantswarm/gsctl \
	-v /home/stevo/git/giantswarm/gsctl/go-build-cache:/.cache \
	-e GOPATH=/go -e GOOS=linux -e GOARCH=amd64 \
	-w /go/src/github.com/giantswarm/gsctl \
	--user 1000:1000 \
	golang:1.13.5-alpine /bin/sh -c "go install github.com/gobuffalo/packr/packr && packr"
Unable to find image 'golang:1.13.5-alpine' locally
1.13.5-alpine: Pulling from library/golang
e6b0cf9c0882: Pull complete 
2848faf0eed1: Pull complete 
0f37312ad70f: Pull complete 
5788d62ee057: Pull complete 
0e6b1d234666: Pull complete 
Digest: sha256:0991060a1447cf648bab7f6bb60335d1243930e38420bee8fec3db1267b84cfa
Status: Downloaded newer image for golang:1.13.5-alpine
failed to initialize build cache at /.cache/go-build: mkdir /.cache/go-build: permission denied
make: *** [Makefile:28: prebuild] Error 1
```

**Comment by marians** [comment]
Yeah, it also failed in CI. Can you please try latest master which includes this change https://github.com/giantswarm/gsctl/pull/488/commits/6fb2292f08d00c8bba5c2842fc90b6cec91c151d ?

**Comment by sslavic** [comment]
Latest master local builds work for me again. Thanks for quick fix!

**Comment by marians** [comment]
Thanks for the confirmation!

**Pull request merged**
