### PR TITLE
Adding command to create and delete a cluster

### PR DESCRIPTION
**Pull request by marians**
This PR adds the commands

- `gsctl create cluster ...`
- `gsctl delete cluster ...`

This can be tested against the API on g8s using `--api-endpoint="https://api-g8s.giantswarm.io"` or a local api.

See https://github.com/giantswarm/giantswarm/issues/984 for general information.

Related: https://github.com/giantswarm/gsclientgen/pull/8

### CODE REVIEW

**Comment by marians** [comment]
FYI The output for a successful execution has changed slightly:

```nohighlight
Requesting new cluster for organization 'mycorp'
New cluster with ID 'vbwka' is launching. You can go ahead and add kubectl credentials using

    gsctl create kubeconfig -c vbwka
```

**Comment by marians** [comment]
This PR now also includes the function to delete a cluster: `gsctl delete cluster ...`

**Comment by marians** [comment]
@oponder Before you get involved in reviewing here, I am currently writing some unit tests and already investing an issue I found through that with interpreting given YAML on cluster creation.

**Comment by marians** [comment]
@oponder I'm done here. Nothing substantial changed.

**Comment by oponder** [comment]
So when I went to delete a cluster, my first guess was to do it like 

```
gsctl delete cluster --api-endpoint http://docker.dev:9000 delete cluster p6b4v
```

Put the error and usage message helped me remember that i needed to do it like

```
gsctl delete cluster --api-endpoint http://docker.dev:9000 delete --cluster p6b4v
```

Beyond that small UX hiccup, LGTM, WFM.

**Comment by oponder** [comment]
Oh, Im also curious how to run tests.

**Comment by marians** [comment]
@oponder Cool that it worked. In the commands up there, the `delete` part appears twice.

To run tests, execute `go test -cover $(glide novendor)`. I have a PR open that adds a make target `gotest`: https://github.com/giantswarm/gsctl/pull/36

The standard command is `go test ./...`, but that would execute tests in `vendor/`, too.

**Comment by oponder** [comment]
Yeah I did a bad copy paste fix because I originally ran it like:

```
$ go run main.go --api-endpoint http://docker.dev:9000 delete cluster -c p6b4v
```

Edited the earlier post

**Pull request merged**
