### PR TITLE
Command to generate bash/zsh completion files

### PR DESCRIPTION
**Pull request by marians**
For https://github.com/giantswarm/gsctl/issues/149

See `gsctl completion -h` for details.

TODO

- [ ] update homebrew recipe

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I get this when sourcing the generated file in my `.zshrc`. 

```
/Users/xh3b4sd/go/src/github.com/giantswarm/gsctl/gsctl-completion-zsh.sh:3: command not found: _arguments
```

**Comment by oponder** [comment]
`bash` instructions work for me! :+1:

**Comment by marians** [comment]
After having a look at spf13/cobra issues, I am not really sure what the status of zsh completion really is. This issue is open: https://github.com/spf13/cobra/issues/107, but it doesn't reflect the status of the API docs.

**Comment by marians** [comment]
I'd like to make bash completion available. As I don't know hoqw to fix the problem with zsh, here are two ways to proceed.

1. Add some info to the usage text and docs that zsh is experimental (not known to work), and users should please provide feedback. We should create an issue and link to it so users have a place where to drop their feedback.
2. Remove zsh from the implementation, usage, and docs.

I prefer 1, as this would maybe help us find out what we'd have to fix. Any opinions?

**Comment by xh3b4sd** [comment]
Go.

**Comment by bpicode** [comment]
@xh3b4sd May I ask: how did you source the zsh completion? I managed to get it working by just copying `gsctl-completion-zsh.sh` to `/usr/share/zsh/vendor-completions/_gsctl`.

**Comment by marians** [comment]
Thanks for the hint @bpicode! Seems like there are several ways to manage completion for zsh. I just pushed a commit that adds some generic setup info to the usage text of the command.

```
The generic installation procedure for zsh is:

1. Rename gsctl-completion-zsh.sh to _gsctl and move it into a directory
   that is part of your $fpath

2. Re-initialize your completion files:

   rm -f ~/.zcompdump; compinit
```

Source: https://github.com/zsh-users/zsh-completions#manual-installation

**Comment by marians** [comment]
@oponder @xh3b4sd I'd like a LGTM here

**Comment by xh3b4sd** [comment]
@bpicode I did what the command output suggested. I put `source gsctl-completion-zsh.sh` in my `.zshcr`.

**Pull request merged**
