### PR TITLE
Use shared gscliauth package

### PR DESCRIPTION
**Pull request by schjan**
What changed on gsctl side?
- Code was moved to giantswarm/gscliauth repository. (Because of that coverage decreased)
- Gopkg.toml was changed accordingly
- spf13/afero was set to a fixed version so that it is compatible to giantswarm/gscliauth and giantswarm/opsctl

_Part of giantswarm/giantswarm#6145 story_

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
LGTM - Please add sig-ux as reviewers as they currently have a big stake in gsctl.

**Comment by marians** [comment]
I'll give this a test today.

So the `spf13/afero` version pinning is forced by opsctl? What's the reason that opsctl needs a specific version?

**Comment by schjan** [comment]
Pinning to `master` in one project and to a version tag in a dependency is not working with `dep`. So we can either go `master` or fixed version.
I decided for fixed version (everything < 2) so we don't have weird dependency issues on a major version change.

**Review by marians — APPROVED** [review]
Works for me

**Pull request merged**
