### PR TITLE
Added support for autoscaling on azure

### PR DESCRIPTION
**Pull request by whites11**
Towards: https://github.com/giantswarm/giantswarm/issues/13200

This PR adds support to node pool autoscaling on azure.

### CODE REVIEW

**Review by fiunchinho — APPROVED** [review]

**Review by axbarsan — COMMENTED** [review]
Can you also update the command description, please?
https://github.com/giantswarm/gsctl/blob/84a73202b212302f2a085d0e598f0a45ba568689/commands/create/nodepool/command.go#L92

Also, there's the node pool update command, as well
https://github.com/giantswarm/gsctl/blob/84a73202b212302f2a085d0e598f0a45ba568689/commands/update/nodepool/command.go#L141

That also needs an update in the docs
https://docs.giantswarm.io/reference/gsctl/update-nodepool/

**Comment by whites11** [comment]
> Can you also update the command description, please?
> https://github.com/giantswarm/gsctl/blob/84a73202b212302f2a085d0e598f0a45ba568689/commands/create/nodepool/command.go#L92
> 
> Also, there's the node pool update command, as well
> https://github.com/giantswarm/gsctl/blob/84a73202b212302f2a085d0e598f0a45ba568689/commands/update/nodepool/command.go#L141
> 
> That also needs an update in the docs
> [docs.giantswarm.io/reference/gsctl/update-nodepool](https://docs.giantswarm.io/reference/gsctl/update-nodepool/)

Done

**Review by axbarsan — APPROVED** [review]
LGTM after fixing the tests 👍🏻

**Comment by axbarsan** [comment]
I found some more, unfortunately:

This is missing for azure:
https://github.com/giantswarm/gsctl/blob/139ed9e088939b6a632c66ec53c2e9b5d9a4ec67/commands/show/nodepool/aws.go#L47

This is also missing for azure:
https://github.com/giantswarm/gsctl/blob/139ed9e088939b6a632c66ec53c2e9b5d9a4ec67/commands/list/nodepools/command.go#L245

**Review by axbarsan — APPROVED** [review]
You're a legend

**Comment by whites11** [comment]
> [Coverage Status](https://coveralls.io/builds/33474358)
> 
> Coverage decreased (-0.04%) to 51.7% when pulling **[bb477cb](https://github.com/giantswarm/gsctl/commit/bb477cbeadef3af857b6d9aa7f824ad85403f548) on azure-np-autoscaling** into **[139ed9e](https://github.com/giantswarm/gsctl/commit/139ed9e088939b6a632c66ec53c2e9b5d9a4ec67) on master**.

@axbarsan Coverage decreased because there is less stuff to test now (edge cases for azure are not present any more).
How can I make coverails happy?

**Comment by axbarsan** [comment]
> How can I make coverails happy?

I'd say to not worry about it, since we're already testing against what's important. Coverage doesn't mean it's less prone to break

**Pull request merged**
