### PR TITLE
gsctl "show cluster" command

### PR DESCRIPTION
**Pull request by marians**
Implementation of https://github.com/giantswarm/gsctl/issues/105

Example output for KVM:

```
./gsctl show cluster o7yst
ID:                            o7yst
Created:                       2017 Nov 20, 13:42 UTC
Organization:                  giantswarm
Kubernetes API endpoint:       https://api.o7yst.REDACTED.kvm.gigantic.io
Release version:               0.3.0
Workers:                       3
CPU cores in workers:          6
RAM in worker nodes (GB):      22.5
Storage in worker nodes (GB):  120
```

Example output for AWS:

```
./gsctl show cluster vxvc7
ID:                            vxvc7
Created:                       2017 Aug 29, 04:26 UTC
Organization:                  giantswarm
Kubernetes API endpoint:       https://api.vxvc7.REDACTED.aws.gigantic.io
Release version:               n/a
Workers:                       3
Worker instance type:          m3.large
CPU cores in workers:          6
RAM in worker nodes (GB):      22.5
Storage in worker nodes (GB):  96
```

### CODE REVIEW

**Comment by marians** [comment]
You mean, adding test cases that yield errors and test for the expected errors?

**Comment by kopiczko** [comment]
Yes.

**Comment by kopiczko** [comment]
Also please make CI green.

**Comment by marians** [comment]
Ah, auto imports... BTW, CIrcleCI is not expected to work. That's an ongoing story.

**Comment by marians** [comment]
Added two more trivial tests

**Pull request merged**
